server:
  port: 8080

spring:
  application:
    name: take-out-food
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/take_out_food
    username: root
    password: xxxx
    # session
    session:
      timeout: 86400
  mvc:
    hiddenmethod:
      filter:
        enabled: true
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false


take-out-food:
  img: D:\img\
